
def print_dragon():
    print("                                    `+                                                                                                                                                                                       ")
    print("                                   `h/                                                                                                       /`                                                                              ")
    print("                                  `yM`                                                                                                       hy                                                                              ")
    print("                                 `yMM`                                                                                                      .NM.                                                                             ")
    print("                                `yMMM`                                                                                                      hMMd`                                                                            ")
    print("                               .dMMMd                                                                                                      :MMMMs                                                                            ")
    print("                              :mMMMMN                                                                                                     `mMMMMMs`                                                                          ")
    print("                            `+NMMMMMM`                                                                                                    sMMMMMMMh`                                                                         ")
    print("                           -hMMMMMMMM`                                                                                                   +MMMMMMMMMm/                                                                        ")
    print("                         `sNMMMMMMMMM.                                                                                                  :NMMMMMMMMMMNy-                                                                      ")
    print("                       `/dMMMMMMMMMMMo                                                                                                 .dMMMMMMMMMMMMMNy-`                                                                   ")
    print("                     `/dMMMMMMMMMMMMMh                                                                                                `yMMMMMMMMMMMMMMMMNd/.`                                                                ")
    print("                   `/dMMMMMMMMMMMMMMMM`                                                                                              `yMMMMMMMMMMMMMMMMMMMMNd+-`                                                             ")
    print("                `.sdMMMMMMMMMMMMMMMMMMo                                                                                              oMMMMMMMMMMMMMMMMMMMMMMMMMmy+:.`                                                        ")
    print("             `.+hNMMMMMMMMMMMMMMMMMMMMN`                                                                                            +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyo+:..`                                                 ")
    print("         `.:ohNMMMMMMMMMMMMMMMMMMMMMMMMs                                                                                           +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhyy/`                                            ")
    print("      -+ydmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-                                                                                         +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.                                             ")
    print("      /dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd`                                                                                       +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd-                                               ")
    print("        /dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                                                                                      /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs                                                 ")
    print("         `sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                                                                                    /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/                                                  ")
    print("           +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/                                                                                  /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-                                                   ")
    print("            -NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                                                                                +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-                                                    ")
    print("             +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs`                                                                             oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/                                                     ")
    print("              yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh`                                                                           oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                                                      ")
    print("              -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm:                                                                         hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                                       ")
    print("               hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs`                                                                      hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+                                                       ")
    print("               +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:                                                                   .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-                                                       ")
    print("               :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh-                                                                .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                                        ")
    print("                NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh-                                                             :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                        ")
    print("                NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh-                                                          +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                        ")
    print("               -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy-`                                                     `sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                        ")
    print("               +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNm+.                                                  `yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-                                                       ")
    print("               sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy:`                                              -dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                                                       ")
    print("              `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhddds`                                     :osmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-                                                      ")
    print("              /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmy/.                                     /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm`                                                     ")
    print("              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+`                                        `./yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                                                     ")
    print("             +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/                                              +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                                                    ")
    print("            `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                                                /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy`                                                  ")
    print("            oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                        :. `-//                   oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.                                                 ")
    print("           /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                      `:sN++hh/`                   `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm:                                                ")
    print("          :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                     .+dMMMNMNo:.                    /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs`                                              ")
    print("          /yhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                   ./hmMMMMMMMMMMmy/`                  dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhy+//`                                              ")
    print("             `./hmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                   +mMMNMMMMMMMMMMMMMd.                 /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNds/-`                                                    ")
    print("                 .omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                  .:NMMMMMMMMMMMMMMMMMMm:                `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho-`                                                        ")
    print("                   .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.               `ohmMMMMNmmMMMMm/sNMMMMMh:                 sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo-                                                            ")
    print("                     yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+                /MMmshh/..yMMMMM: hMMMMMM/                 /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd/.                                                              ")
    print("                      sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                :o:   `.sNMMMMMd` :MMMMMMm                  NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs`                                                                ")
    print("                      `hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm:             ``.:`.--:oMMMMMMm-  /MMMMMM/                  NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh.                                                                  ")
    print("                       -NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.        ..`-::-.` -sNMMMNd/.  .mMMMMMm`                  NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+                                                                    ")
    print("                        +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo`       `..`    -sddNy+-    `yMMMMMM+                  `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-                                                                     ")
    print("                        `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh:`                 .      `yMMMMMMMh                 .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-                                                                      ")
    print("                         yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo`                     .hMMMMMMM+`              `:omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-                                                                       ")
    print("                         -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo-                  -mMMMMMMMd`           `-+ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/                                                                        ")
    print("                         .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh+`              /NMMMMMMMM/        `:ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                                                                         ")
    print("                          hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+.          /MMMMMMMMMN`   .-oyhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd                                                                          ")
    print("                          hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhooo---/yMMMMMMMMMMNhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                                                          ")
    print("                          hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd                                                                           ")
    print("                          -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                                                           ")
    print("                          -MMMMMMMMMMMMMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                                                            ")
    print("                          -MMMMMMMmho/-.       .-:oshdNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                                                            ```-:::::::.````")
    print("                          -MMMNho-                    `.-+sdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+                                                     `:/oyddNNNMMMMMMMMNNNNN")
    print("                          oMmo-                            ``-/ohmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                 `:ohmNMMMMMMMMMMNmhy++++:---")
    print("                          s+`                                    `./yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdys+:--```````--:++ydmMMMMMMMMMMMMMMMMMMMN                                             `-+hmMMMMMMMMMMNdy+-.`          ")
    print("                          `                                          -yMMMMMMMMMMMMMMMMMMMMMMMMMNds/-``                   ``-/oydNMMMMMMMMMMMMMN                                          `:smNMMMMMMMMMNds/.`               ")
    print("                                                                       -dMMMMMMMMMMMMMMMMMMMMNh/.`                              `./ohNMMMMMMMMMo                                        -smNMMMMMMMMMmy/.`                   ")
    print("                                                                        `dMMMMMMMMMMMMMMMMMMm-                                       .:ohmMMMMMo                                     `+dNMMMMMMMMMms-`                       ")
    print("                                                                         -NMMMMMMMMMMMMMMMMN-                                            .:ydMMo                                   -ymMMMMMMMMMmy-`                          ")
    print("                                                                          sMMMMMMMMMMMMMMMMm.                                               `.o:                                 -yNMMMMMMMMMho.                             ")
    print("                                                                          :MMMMMMMMMMMMMMMMMh`                                                                                 -yNMMMMMMMMMh:                                ")
    print("                                                                           mMMMMMMMMMNsMMMMMMd:                                                                              -sNMMMMMMMMMh:                                  ")
    print("                                                                           mMMMMMMMMm:yMMMMMMMNs`                                                                          `sNMMMMMMMMMh:`                                   ")
    print("                                                                           mMMMMMMMm-:NMMMMMMMMMh.                                                                       `/dMMMMMMMMMh:`                                     ")
    print("                                                                           mMMMMMMN-`dMMMMMMMMMMMd.                                                                     .yMMMMMMMMMN/`                                       ")
    print("                                                                           mMMMMMMo :MMMMMMMMMMMMMh`                                                                   /NMMMMMMMMMy.                                         ")
    print("                                                                           mMMMMMM. yMMMMMMMMMMMMMMo                                                                 .sMMMMMMMMMN/`                                          ")
    print("                                                                           mMMMMMM``mMMMMMMMMMMMMMMM-                                                               :dMMMMMMMMMd-                                            ")
    print("                                                                          :NMMMMMMo +MMMMMmdMMMMMMMMm`                                                             :NMMMMMMMMMs`                                             ")
    print("                                                                          dMMMMMMMN- yMMMMd:MMMMMMMMMd`                                                          `oMMMMMMMMMMs`                                              ")
    print("                                                                          mMMMMMMMMm: oNMMM/dMMMMMMMMMs                                                          sMMMMMMMMMN+`                                               ")
    print("                                                                          yMMMMMMMMMMo`:dMMN+ymMMMMMMMM/                                                        sMMMMMMMMMM+                                                 ")
    print("                                                                     ```` -ydhsyyyyyyy- `dMMN+.:hMMMMMMm`                                                      sMMMMMMMMMMs                                                  ")
    print("                                                                 `-oydmmmhs/:symmmmmmmyyyNMMMM/ /MMMMMMM+                                                     sMMMMMMMMMMy`                                                  ")
    print("                                                                 oomMMMNNMMMMMNNddhssssshdmNMN. /MMMMMMMm                                                    +MMMMMMMMMMd.                                                   ")
    print("                                                                  .mho:`-NMmh/.:+yhmdhhs+-.-/:  /MMMMMMMN                                                   :NMMMMMMMMMN-                                                    ")
    print("                                                                   `    :No``sNMMMN+oMMMMMNmyo:`+MMMMMMMN                                                  .mMMMMMMMMMMs                                                     ")
    print("                                                                         `   dMMMM: `dMMMMMMMMMNNMMMMMMMN                                                 `hMMMMMMMMMMd                                                      ")
    print("                                                                             -MMMN   yMMMMMMMMMMMMMMMMMMN                                                `yMMMMMMMMMMN-                                                      ")
    print("                                                                              sMMN   hMMMMMMMMMMMMMMMMMM+                                                oMMMMMMMMMMMs                                                       ")
    print("                                                                              +MMN  -MMMMMMMMMMMMMMMMMMN`                                               oMMMMMMMMMMMm                                                        ")
    print("                                                                             /mMMM.`dMMMMMMMMMMMMMMMMMM+                                               oMMMMMMMMMMMM-                                                        ")
    print("                                                                         ./ymMMMMN-hMMMMMMMMMMMMMMMMMMd                                               +MMMMMMMMMMMMs                                                         ")
    print("                                                                   `.:ohmMMMMMNds.-MMMMMMMMMMMMMMMMMMM/                                             `yMMMMMMMMMMMMm                                                          ")
    print("                                                              `-/sdNNMMMNhs+/-`   sMMMMMMMMMMMMMMMMMMM                                             .hMMMMMMMMMMMMM:                                                          ")
    print("                                                       -oyddddNNMMMMMh+.`         sMMMMMMMMMMMMMMMMMMM                                            :mMMMMMMMMMMMMMs                                                           ")
    print("                                                      +NmMMMMMMMMMMh-             sMMMMMMMMMMMMMMMMMMM                                          `sNMMMMMMMMMMMMMd`                                                           ")
    print("                                                      y/.NMMMMMMMmo`              sMMMMMMMMMMMMMMMMMMM`                                       `+mMMMMMMMMMMMMMMN.                                                            ")
    print("                                                      ` /MMNMMd:.`                :MMMMMMMMMMMMMMMMMMMo                                     `+mMMMMMMMMMMMMMMMMo                                                             ")
    print("                                                        `Nm.yM+                   `NMMMMMMMMMMMMMMMMMMN.                                  .+mMMMMMMMMMMMMMMMMMy                                                              ")
    print("                                                         s- `y+                    sMMMMMMMMMMMMMMMMMMMh.                              `:yNMMMMMMMMMMMMMMMMMMh`                                                              ")
    print("                                                         `   `.                    .MMMMMMMMMMMMMMMMMMMMm-                          .:ymMMMMMMMMMMMMMMMMMMMMm.                                                               ")
    print("                                                                                    yMMMMMMMMMMMMMMMMMMMMNy-                    `-+yNMMMMMMMMMMMMMMMMMMMMMMm-                                                                ")
    print("                                                                                    -MMMMMMMMMMMMMMMMMMMMMMNy+.`           `.:/ymNMMMMMMMMMMMMMMMMMMMMMMMMm-                                                                 ")
    print("                                                                                     sMMMMMMMMMMMMMMMMMMMMMMMMNdys+//////sydmMMMMMMMMMMMMMMMMMMMMMMMMMMMMh.                                                                  ")
    print("                                                                                     .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.                                                                   ")
    print("                                                                                      /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+`                                                                    ")
    print("                                                                                       oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy-                                                                      ")
    print("                                                                                       `hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+                                                                        ")
    print("                                                                                        `hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+`                                                                         ")
    print("                                                                                         `hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+`                                                                           ")
    print("                                                                                          `+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh:                                                                              ")
    print("                                                                                            -yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmo.                                                                                ")
    print("                                                                                              /dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmh:`                                                                                  ")
    print("                                                                                                -yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh/.                                                                                     ")
    print("                                                                                                  .+dNMMMMMMMMMMMMMMMMMMMMMMMMMMNmy/.                                                                                        ")
    print("                                                                                                     ./sdNMMMMMMMMMMMMMMMMMMNdy+-                                                                                            ")
    print("                                                                                                         .:+osdddmNNddddss::`                                                                                                ")
    print("                                                                                                                  ``                                                                                                         ")
    print("                                                                                                                                                                                                                             ")
    print("                                                                                                                                                                                                                             ")
    print("                                                                                                                                                                                                                             ")

def print_dragon_v2():
    print("           +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/                                                                                  /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-                                                   ")
    print("            -NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                                                                                +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-                                                    ")
    print("             +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs`                                                                             oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/                                                     ")
    print("              yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh`                                                                           oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                                                      ")
    print("              -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm:                                                                         hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                                       ")
    print("               hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs`                                                                      hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+                                                       ")
    print("               +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:                                                                   .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-                                                       ")
    print("               :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh-                                                                .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                                        ")
    print("                NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh-                                                             :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                        ")
    print("                NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh-                                                          +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                        ")
    print("               -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy-`                                                     `sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                        ")
    print("               +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNm+.                                                  `yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-                                                       ")
    print("               sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy:`                                              -dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                                                       ")
    print("              `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhddds`                                     :osmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-                                                      ")
    print("              /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmy/.                                     /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm`                                                     ")
    print("              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+`                                        `./yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                                                     ")
    print("             +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/                                              +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                                                    ")
    print("            `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                                                /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy`                                                  ")
    print("            oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                        :. `-//                   oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.                                                 ")
    print("           /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                      `:sN++hh/`                   `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm:                                                ")
    print("          :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                     .+dMMMNMNo:.                    /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs`                                              ")
    print("          /yhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                   ./hmMMMMMMMMMMmy/`                  dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhy+//`                                              ")
    print("             `./hmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                   +mMMNMMMMMMMMMMMMMd.                 /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNds/-`                                                    ")
    print("                 .omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                  .:NMMMMMMMMMMMMMMMMMMm:                `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho-`                                                        ")
    print("                   .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.               `ohmMMMMNmmMMMMm/sNMMMMMh:                 sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo-                                                            ")
    print("                     yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+                /MMmshh/..yMMMMM: hMMMMMM/                 /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd/.                                                              ")
    print("                      sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                :o:   `.sNMMMMMd` :MMMMMMm                  NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs`                                                                ")
    print("                      `hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm:             ``.:`.--:oMMMMMMm-  /MMMMMM/                  NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh.                                                                  ")
    print("                       -NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.        ..`-::-.` -sNMMMNd/.  .mMMMMMm`                  NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+                                                                    ")
    print("                        +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo`       `..`    -sddNy+-    `yMMMMMM+                  `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-                                                                     ")
    print("                        `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh:`                 .      `yMMMMMMMh                 .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-                                                                      ")
    print("                         yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo`                     .hMMMMMMM+`              `:omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-                                                                       ")
    print("                         -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo-                  -mMMMMMMMd`           `-+ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/                                                                        ")
    print("                         .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh+`              /NMMMMMMMM/        `:ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                                                                         ")
    print("                          hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+.          /MMMMMMMMMN`   .-oyhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd                                                                          ")
    print("                          hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhooo---/yMMMMMMMMMMNhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                                                          ")
    print("                          hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd                                                                           ")
    print("                          -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                                                           ")
    print("                          -MMMMMMMMMMMMMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                                                            ")
    print("                          -MMMMMMMmho/-.       .-:oshdNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                                                            ```-:::::::.````")
    print("                          -MMMNho-                    `.-+sdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+                                                     `:/oyddNNNMMMMMMMMNNNNN")
    print("                          oMmo-                            ``-/ohmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                 `:ohmNMMMMMMMMMMNmhy++++:---")
    print("                          s+`                                    `./yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdys+:--```````--:++ydmMMMMMMMMMMMMMMMMMMMN                                             `-+hmMMMMMMMMMMNdy+-.`          ")
    print("                          `                                          -yMMMMMMMMMMMMMMMMMMMMMMMMMNds/-``                   ``-/oydNMMMMMMMMMMMMMN                                          `:smNMMMMMMMMMNds/.`               ")
    print("                                                                       -dMMMMMMMMMMMMMMMMMMMMNh/.`                              `./ohNMMMMMMMMMo                                        -smNMMMMMMMMMmy/.`                   ")
    print("                                                                        `dMMMMMMMMMMMMMMMMMMm-                                       .:ohmMMMMMo                                     `+dNMMMMMMMMMms-`                       ")
    print("                                                                         -NMMMMMMMMMMMMMMMMN-                                            .:ydMMo                                   -ymMMMMMMMMMmy-`                          ")
    print("                                                                          sMMMMMMMMMMMMMMMMm.                                               `.o:                                 -yNMMMMMMMMMho.                             ")
    print("                                                                          :MMMMMMMMMMMMMMMMMh`                                                                                 -yNMMMMMMMMMh:                                ")
    print("                                                                           mMMMMMMMMMNsMMMMMMd:                                                                              -sNMMMMMMMMMh:                                  ")
    print("                                                                           mMMMMMMMMm:yMMMMMMMNs`                                                                          `sNMMMMMMMMMh:`                                   ")
    print("                                                                           mMMMMMMMm-:NMMMMMMMMMh.                                                                       `/dMMMMMMMMMh:`                                     ")
    print("                                                                           mMMMMMMN-`dMMMMMMMMMMMd.                                                                     .yMMMMMMMMMN/`                                       ")
    print("                                                                           mMMMMMMo :MMMMMMMMMMMMMh`                                                                   /NMMMMMMMMMy.                                         ")
    print("                                                                           mMMMMMM. yMMMMMMMMMMMMMMo                                                                 .sMMMMMMMMMN/`                                          ")
    print("                                                                           mMMMMMM``mMMMMMMMMMMMMMMM-                                                               :dMMMMMMMMMd-                                            ")
    print("                                                                          :NMMMMMMo +MMMMMmdMMMMMMMMm`                                                             :NMMMMMMMMMs`                                             ")
    print("                                                                          dMMMMMMMN- yMMMMd:MMMMMMMMMd`                                                          `oMMMMMMMMMMs`                                              ")
    print("                                                                          mMMMMMMMMm: oNMMM/dMMMMMMMMMs                                                          sMMMMMMMMMN+`                                               ")
    print("                                                                          yMMMMMMMMMMo`:dMMN+ymMMMMMMMM/                                                        sMMMMMMMMMM+                                                 ")
    print("                                                                     ```` -ydhsyyyyyyy- `dMMN+.:hMMMMMMm`                                                      sMMMMMMMMMMs                                                  ")
    print("                                                                 `-oydmmmhs/:symmmmmmmyyyNMMMM/ /MMMMMMM+                                                     sMMMMMMMMMMy`                                                  ")
    print("                                                                 oomMMMNNMMMMMNNddhssssshdmNMN. /MMMMMMMm                                                    +MMMMMMMMMMd.                                                   ")
    print("                                                                  .mho:`-NMmh/.:+yhmdhhs+-.-/:  /MMMMMMMN                                                   :NMMMMMMMMMN-                                                    ")
    print("                                                                   `    :No``sNMMMN+oMMMMMNmyo:`+MMMMMMMN                                                  .mMMMMMMMMMMs                                                     ")
    print("                                                                         `   dMMMM: `dMMMMMMMMMNNMMMMMMMN                                                 `hMMMMMMMMMMd                                                      ")
    print("                                                                             -MMMN   yMMMMMMMMMMMMMMMMMMN                                                `yMMMMMMMMMMN-                                                      ")
    print("                                                                              sMMN   hMMMMMMMMMMMMMMMMMM+                                                oMMMMMMMMMMMs                                                       ")
    print("                                                                              +MMN  -MMMMMMMMMMMMMMMMMMN`                                               oMMMMMMMMMMMm                                                        ")
    print("                                                                             /mMMM.`dMMMMMMMMMMMMMMMMMM+                                               oMMMMMMMMMMMM-                                                        ")
    print("                                                                         ./ymMMMMN-hMMMMMMMMMMMMMMMMMMd                                               +MMMMMMMMMMMMs                                                         ")
    print("                                                                   `.:ohmMMMMMNds.-MMMMMMMMMMMMMMMMMMM/                                             `yMMMMMMMMMMMMm                                                          ")
    print("                                                              `-/sdNNMMMNhs+/-`   sMMMMMMMMMMMMMMMMMMM                                             .hMMMMMMMMMMMMM:                                                          ")
    print("                                                       -oyddddNNMMMMMh+.`         sMMMMMMMMMMMMMMMMMMM                                            :mMMMMMMMMMMMMMs                                                           ")
    print("                                                      +NmMMMMMMMMMMh-             sMMMMMMMMMMMMMMMMMMM                                          `sNMMMMMMMMMMMMMd`                                                           ")
    print("                                                      y/.NMMMMMMMmo`              sMMMMMMMMMMMMMMMMMMM`                                       `+mMMMMMMMMMMMMMMN.                                                            ")
    print("                                                      ` /MMNMMd:.`                :MMMMMMMMMMMMMMMMMMMo                                     `+mMMMMMMMMMMMMMMMMo                                                             ")
    print("                                                        `Nm.yM+                   `NMMMMMMMMMMMMMMMMMMN.                                  .+mMMMMMMMMMMMMMMMMMy                                                              ")
    print("                                                         s- `y+                    sMMMMMMMMMMMMMMMMMMMh.                              `:yNMMMMMMMMMMMMMMMMMMh`                                                              ")
    print("                                                         `   `.                    .MMMMMMMMMMMMMMMMMMMMm-                          .:ymMMMMMMMMMMMMMMMMMMMMm.                                                               ")
    print("                                                                                    yMMMMMMMMMMMMMMMMMMMMNy-                    `-+yNMMMMMMMMMMMMMMMMMMMMMMm-                                                                ")
    print("                                                                                     sMMMMMMMMMMMMMMMMMMMMMMMMNdys+//////sydmMMMMMMMMMMMMMMMMMMMMMMMMMMMMh.                                                                  ")
    print("                                                                                     .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.                                                                   ")
    print("                                                                                      /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+`                                                                    ")
    print("                                                                                       oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy-                                                                      ")
    print("                                                                                       `hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+                                                                        ")
    print("                                                                                        `hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+`                                                                         ")

def print_small_dragon():
    print('          :d                                .m`                               ')
    print('         oMd                                hMd`                              ')
    print('       :mMMN                               oMMMNo.                            ')
    print('    `+dMMMMM.                             /MMMMMMMds/-`                       ')
    print('  odMMMMMMMMm`                           /MMMMMMMMMMMMMs`                     ')
    print('   oMMMMMMMMMh                          /MMMMMMMMMMMMM.                       ')
    print('    sMMMMMMMMMh`                       +MMMMMMMMMMMMM/                        ')
    print('    `MMMMMMMMMMN/                     sMMMMMMMMMMMMMm                         ')
    print('     NMMMMMMMMMMMm/                 `yMMMMMMMMMMMMMMh                         ')
    print('    .MMMMMMMMMMMMMMmo/-            :dMMMMMMMMMMMMMMMN`                        ')
    print('    sMMMMMMMMMMMMMMMN.            `+NMMMMMMMMMMMMMMMMh                        ')
    print('   -MMMMMMMMMMMMMMMN-      -+/`     :MMMMMMMMMMMMMMMMMh.                      ')
    print('   -+hMMMMMMMMMMMMN-     /mMMMd.     dMMMMMMMMMMMMMMho:.                      ')
    print('      :NMMMMMMMMMM/    `ysyMdsMd     /MMMMMMMMMMMN+`                          ')
    print('       /MMMMMMMMMMm.  `.`/ms.yMs     :MMMMMMMMMMy`                            ')
    print('        mMMMMMMMMMMMh.      sMN-   -+mMMMMMMMMMy                              ')
    print('        yMMMMMMMMMMMMMNs/::hMMd+shNMMMMMMMMMMMm                               ')
    print('        oMMNmddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/                               ')
    print('        os-      `:+ymMMMMMMMMMMMNdhhdNMMMMMMM`              .+sdmdys+///::-` ')
    print('                      :mMMMMMNo-`      `-+ymMN            -smMms:`            ')
    print('                       -MMMMMo              ./          :dMMy-                ')
    print('                        MMNyMMy                       -dMMs.                  ')
    print('                        MM/NMMMy                     sMMd.                    ')
    print('                       -MModMdMM+                  .dMMy                      ')
    print('                     `:/hdm+hmsMM-                .mMMs                       ')
    print('                    `++hydhhhy-MMo               `dMMd                        ')
    print('                        .M-dMMMMMo               hMMN.                        ')
    print('                       .+N+MMMMMN`              yMMM+                         ')
    print('                 .++sds+:`yMMMMMs             .hMMMd                          ')
    print('                 -mNo.    sMMMMMh           `oNMMMN.                          ')
    print('                  ..      -MMMMMMs`      `/yNMMMMM.                           ')
    print('                           hMMMMMMNyoooydMMMMMMMN.                            ')
    print('                           `NMMMMMMMMMMMMMMMMMMy.                             ')
    print('                            .dMMMMMMMMMMMMMMNy-                               ')
    print('                              /dMMMMMMMMMMd+`                                 ')
    print('                                ./syhyyo:`                                    ')

def print_green_kiwi():
    print('------------------------------------------------------------------------------\n')
    print('                                          .:/+ssyyhhhhhhyyso+/:.`             ')
    print('                                     `:+shhhhhhhhhhhhhhhhhhhhhhhhyo+:`        ')
    print('                                  ./shhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhy+-     ')
    print('                               `:shhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh+.  ')
    print('                `-://///::---:ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhho ')
    print('             .+yhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('            +hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('           ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('          -hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('          ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('          yhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('         `hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('          yhhhhhhhhhhhhhhy+shhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('         .hhhhhhhhhhhyo/-   +hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('        :hhhs///::-.`        -yhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('       ohhy:                   :yhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('     `shho`                      :shhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('    `shh/                          ./yhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('    ohh:                              ./oyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh ')
    print('   /hh/                                   .:+oyhhhhhhhhhhhhhhhhhhhhhhhhhhhhs: ')
    print('  .hh+                                         `.-+hhhhhhhhhhhhhhhhhhhhhy+.   ')
    print('  +hy                                             /hhhy:.-:+yhhhhhhhhho.      ')
    print(' `hh-                                             yhhh.     `shhhhhho.        ')
    print(' -h+                                             .hhh/       `hhhhy-          ')
    print(' /h`                                             /hhh`        yhhy`           ')
    print(' :/                                        `:+osyhhhy         hhh.            ')
    print('                                          +hhsyhhyo++-     `-ohhy             ')
    print('                                         :+.  /o.    .:/osyhhhhhh.            ')
    print('                                              `    .ooo++ohhhhsooo.           ')
    print('                                                         +o:.                 ')
